language: node_js
node_js: '10'
cache: yarn
env:
  global:
    - FORCE_COLOR=1
jobs:
  include:
    - stage: test
      script:
        - npm run prettier-check
        - npm run typecheck
        - npm run eslint
        - npm run build
        - npm run cover
        - nyc report --reporter json
        - 'bash <(curl -s https://codecov.io/bash)'
stages:
  - test
branches:
  only:
    - master
    - /^renovate\//
